apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: service-messer-traffic-split
  namespace: mkdev
spec:
  service: service-messer
  backends:
  - service: service-messer
    weight: 500
  - service: service-messer-v2
    weight: 500
